[issue #1] Add a plugin
minebul/kubectl-decode pull request #2
Opened 2024-07-24 13:57 UTC by minebul

2024-09-29 23:49 UTC, geal6704 requested changes

2024-09-29 23:49 UTC, geal6704 commented on README.md
> +
test

2024-10-26 14:30 UTC, geal6704 requested changes

2024-10-26 14:30 UTC, geal6704 commented on README.md
> +# Install
Add information about cloning this repo and making `install.sh` executable `chmod +x install.sh`

2024-10-26 14:30 UTC, geal6704 commented on README.md
> +    h) Display help.
Add `help`, so the user can use `decode -h` and `decode help`

2024-10-26 14:30 UTC, geal6704 commented on install.sh
> +echo -e "\nDone.\n"
Make it not "Done", but "Plugin installed"

2024-10-26 14:30 UTC, geal6704 commented on kubectl-decode
> +                echo -e "ERROR: \"${FORMAT}\" is wrong output format. Supported are: \"json\", \"yaml\"\n"
"Supported are" ~> "Supported formats are"

2025-01-16 12:05 UTC, minebul commented on README.md
> +    h) Display help.
Too much to do for now

2025-01-16 12:05 UTC, minebul commented on README.md
> +# Install
Git stores info about whether file executable or not

2025-01-16 12:09 UTC, merged